# Generated by Django 5.0.6 on 2024-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
    ]
