# Generated by Django 5.0.6 on 2024-05-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_borrowed',
        ),
    ]
